### ISSUE TITLE
NavBar Movement Distorts Upon Inserting Text Editor Plugin

### ISSUE THREAD

**Issue by JustinSomers** [creativetimofficial/bootstrap-wizard#7]
Hello,

I currently am running into an issue where the navbar's movement distorts upon switching to a panel that has my custom text editor on it.  When I remove the text editor from my html, the wizard returns back to it's normal state.   I am using the text editor plugin, summernote.

The tab for the middle view (the one that is causing the issue) is in a partial view.
![capturewizard](https://user-images.githubusercontent.com/17032721/28073862-a694b4ea-661c-11e7-999a-74c2417a3d28.PNG)

            '<div class="col-md-10">
                <textarea id="taBody"></textarea> @* This is where the text editor is loaded, displays fine when this line is removed.*@
            </div>
            <div class="col-md-2">
                <input type="button" id="editBody" onclick="bodyEditor()" class="btn btn-default" value="Edit" />
                <input type="button" id="saveBody" onclick="bodySave()" class="btn btn-default" value="Save" />
            </div>'

Any thoughts on what may be happening?  Thanks!

**Comment by alexandru-paduraru** [comment]
@JustinSomers thank you for using our wizard and sorry for the late response. Please go to gsdk-bootstrap-wizard.js on line 80 you will find this code:

`var $total = navigation.find('li').length;` replace it with this one `var $total = navigation.find('.nav li').length;` then everything will work fine.

Best,
Alex

**Comment by mscottfowler** [comment]
Thank you so much! I will try that. I appreciate the help!

Scott Fowler
505-985-1960

**Comment by JustinSomers** [comment]
Hello, I was able to fix the result with a slightly different approach.  For future reference for others who may be looking into this issue:  Here's what caused the issue for my case.

In the refreshAnimation() function there is a line of code here:
`
function refreshAnimation($wizard, index){
    total_steps = $wizard.find('li').length;
    move_distance = $wizard.width() / total_steps;
    step_width = move_distance;
    move_distance *= index;

    $wizard.find('.moving-tab').css('width', step_width);
    $('.moving-tab').css({
        'transform':'translate3d(' + move_distance + 'px, 0, 0)',
        'transition': 'all 0.3s ease-out'

    });`

However, if you have any list items within the wizard (in my case, I have a large drop down list), it also ends up selecting those.  So in my case, total_steps was returning a value of 144 instead of a value of 3.  As a result, the width shrinks of the orange selector shrinks, along with how much is moves.

So I did a temporary fix by changing the total_steps line to 'total_steps = $wizard.find('ul.wizard-tabList > li').length;'

which results in this revised function:
'function refreshAnimation($wizard, index){
    total_steps = $wizard.find('ul.wizard-tabList > li').length;
    move_distance = $wizard.width() / total_steps;
    step_width = move_distance;
    move_distance *= index;

    $wizard.find('.moving-tab').css('width', step_width);
    $('.moving-tab').css({
        'transform':'translate3d(' + move_distance + 'px, 0, 0)',
        'transition': 'all 0.3s ease-out'

    });
}'

...and so I need to add a class to my unordered list tag in the actual html code to look like this:
<div class="wizard-navigation">
    <ul class="wizard-tabList">
               <li><a href="#select" data-toggle="tab">Select</a></li>
               <li><a href="#create" data-toggle="tab">Edit</a></li>
                <li><a href="#schedule" data-toggle="tab">Schedule</a></li>
    </ul>
</div>
Let me know if anyone has any other ideas on how to improve this!

I attempted to fork it to show the code here, but I'm pretty new to GitHub, so let me know if I did this wrong.

https://github.com/JustinSomers/bootstrap-wizard/blob/master/assets/js/gsdk-bootstrap-wizard.js

Anyways, thanks for the awesome plugin and the support!
